### ISSUE TITLE
它看起来像是有一个‘signale’模块引用，但是未在’package.json‘声明？

### ISSUE THREAD

**Issue by songyazhao** [Lizhooh/find-file-ext#1]
node@8.11.1

复现步骤：

1、
> npm install find-file-ext

2、
> require('find-file-ext')

3、
```bash
module.js:549
    throw err;
    ^

Error: Cannot find module 'signale'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\GitHubOther\Plz-shop\admin\node_modules\find-file-ext\index.js:4:17)    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by Lizhooh** [comment]
已经修复了。
